In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## Methods

Functions that belong to Python objects. Specific for each type of object. For example for 'str' you can have methods like 'capitalise()' or 'replace()'.

In [3]:
x = ['bathroom',17.9,'kitchen',18.0,'living room',23.5]   #A list

In [4]:
x.index(18.0)   #Find the index in the list of the number you want

3

In [5]:
x.count(18.0)  #Counts how many times the number appears in the list

1

In [6]:
len(x)    #A function

6

In [7]:
y = 'simona'   #A string

In [8]:
y.capitalize()

'Simona'

In [9]:
y.replace('a','elu')

'simonelu'

In [10]:
y.upper()

'SIMONA'

In [11]:
y.count('m')

1

In [12]:
x.append('me')  #Only takes one argument

In [13]:
x

['bathroom', 17.9, 'kitchen', 18.0, 'living room', 23.5, 'me']

In [14]:
x.append(19.0)

If you need a guide of what methods are available for an object, just type for example 'help(str)'.

In [15]:
x.reverse()

In [16]:
x

[19.0, 'me', 23.5, 'living room', 18.0, 'kitchen', 17.9, 'bathroom']

## Packages

Directory of Python scripts. Each script is a module which specify functions, methods or types.
\\ NumPy - for arrays;
\\ Matplotlib - for plotting;
\\ scikit-learn - for ML;

pip3 install numpy

import numpy as np

from numpy import array    #less preffered sometimes in a big code

## NumPy

Fast mathematical operations over collections.

Numeric Python.

NumPy array can only contain one type!

In [17]:
list = [1,2,3]

In [18]:
np_array = np.array([1,2,3])

In [19]:
python_list = list +list
print(python_list)

[1, 2, 3, 1, 2, 3]


In [20]:
python_array = np_array + np_array
print(python_array)

[2 4 6]


In [21]:
bmi = np.array([20.876,21.765,25.678,24.987,23.875])

In [22]:
bmi[1]

21.765

In [23]:
bmi>23

array([False, False,  True,  True,  True])

In [24]:
bmi[bmi>23]

array([25.678, 24.987, 23.875])

### NumPy 2D arrays

In [25]:
np_2d = np.array([[1.73,1.68,1.90], [53.5,65.1,90.8]])

In [26]:
np_2d

array([[ 1.73,  1.68,  1.9 ],
       [53.5 , 65.1 , 90.8 ]])

In [27]:
np_2d.shape   #This is not a method

(2, 3)

In [28]:
np_2d[0]  #Gives you row

array([1.73, 1.68, 1.9 ])

In [29]:
np_2d[0][1] #Row/column

1.68

In [30]:
np_2d[0,1]

1.68

In [31]:
np_2d[:,1:3] #Both rowss & 2nd and 3rd column

array([[ 1.68,  1.9 ],
       [65.1 , 90.8 ]])

In [32]:
np_2d[1,:] #Second row, all columns

array([53.5, 65.1, 90.8])

### NumPy: Basic Statistics

In [33]:
np.mean(np_2d[1,:])

69.8

In [34]:
np.median(np_2d[1,:]) #Weight of the median person

65.1

In [35]:
np.std(np_2d[1,:])

15.58610492286853

In [36]:
np.corrcoef(np_2d[0,:],np_2d[1,:])  #Check if the first row (height) and the second row (weigth) are correlated

array([[1.       , 0.8642027],
       [0.8642027, 1.       ]])

In [37]:
#Generate some height and weight data
height = np.round(np.random.normal(1.75,0.2,5000),2)
weight = np.round(np.random.normal(60.3,15,5000),2)

In [38]:
np_city = np.column_stack((height,weight))  #Paste the two as columns

In [39]:
np_city

array([[ 1.75, 71.43],
       [ 2.03, 55.52],
       [ 1.6 , 79.39],
       ...,
       [ 1.84, 65.06],
       [ 1.79, 56.63],
       [ 1.93, 69.11]])